package esprit.tn;


import static com.codename1.ui.CN.*;

import Forms.AjouterAbonnement;
import Forms.AjouterEnfant;
import Forms.ConsulterClub;
import Forms.ConsulterEnfant;
import com.codename1.ui.*;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import com.codename1.ui.layouts.BoxLayout;

import java.io.IOException;
import java.net.URISyntaxException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
    public MyApplication fo;
    private Form current;
    private Resources theme;

    public void init(Object context) {
        fo=this;
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        Button b=new Button("ajouter enfant");
        b.addActionListener(e->new AjouterEnfant(fo).show());

        Button bs=new Button("ajouter abonnement");
        bs.addActionListener(s->new AjouterAbonnement(fo).show());
        Button bv=new Button("Consulter enfants");
        bv.addActionListener(s->new ConsulterEnfant(fo).show());

      /* Button consulterClubs=new Button("Consulter Clubs");
        bs.addActionListener(s-> {
            try {
                new ConsulterClub(fo).show();
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        });*/
        hi.addAll(b,bs,bv);

        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
